# Generated by Django 5.0.6 on 2024-06-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjapp", "0007_attendance_teacher_teacher_class_teacher_of_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jjapp.teacher"
            ),
        ),
    ]
